server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: ACCOUNT-SERVICE
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account/**
          filters:
            - RewritePath=/account/(?<path>.*), /$\{path}
        - id: NOMINATION-SERVICE
          uri: lb://NOMINATION-SERVICE
          predicates:
            - Path=/nomination/**
          filters:
            - RewritePath=/nomination/(?<path>.*), /$\{path}
        - id: NOTIFICATION-SERVICE
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification/**
          filters:
            - RewritePath=/notification/(?<path>.*), /$\{path}
        - id: REWARD-SERVICE
          uri: lb://REWARD-SERVICE
          predicates:
            - Path=/reward/**
          filters:
            - RewritePath=/reward/(?<path>.*), /$\{path}
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employee/**
          filters:
            - RewritePath=/employee/(?<path>.*), /$\{path}
  config:
    import: configserver:http://localhost:9296


springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: employee
        url: /v3/api-docs/employee
      - name: account
        url: /v3/api-docs/account
      - name: reward
        url: /v3/api-docs/reward
      - name: nomination
        url: /v3/api-docs/nomination
      - name: notification
        url: /v3/api-docs/notification