server:
  port: 9002

spring:
  application:
    name: NOMINATION-SERVICE
  config:
    import: configserver:http://localhost:9296
  zipkin:
    base_url: http://127.0.0.1:9411/

springdoc:
  packagesToScan: com.rewards